version: '3'
services:
  limehome-api:
    container_name: limehome-api
    build:
      context: ../
      dockerfile: ./infrastructure/app/Dockerfile
    networks:
      limehome:
    ports:
      - 3000:3000

  limehome-database:
    container_name: limehome-database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    networks:
      limehome:
    ports:
      - 5432:5432

networks:
  limehome: